[tool.black]
line-length = 100

[tool.isort]
profile = 'black'
skip_gitignore = false
line_length = 100
atomic = true
sections = ['FUTURE', 'STDLIB', 'THIRDPARTY', 'LOCALFOLDER', 'FIRSTPARTY']
known_local_folder = ['src']

[tool.poetry]
name = "df-analyze"
version = "0.1.0"
description = ""
authors = ["Derek M Berger <dmberger.dev@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.8,<3.10"
matplotlib = "^3.4.1"
numpy = "^1.20.2"
pandas = "^1.2.4"
scikit-learn = "^0.24.2"
scipy = "^1.6.3"
typing-extensions = "^3.7.4"
featuretools = "^0.23.3"
optuna = "^2.7.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
