[tool.black]
line-length = 100

[tool.isort]
profile = 'black'
skip_gitignore = false
line_length = 100
atomic = true
sections = ['FUTURE', 'STDLIB', 'THIRDPARTY', 'LOCALFOLDER', 'FIRSTPARTY']
known_local_folder = ['src']

[tool.poetry]
name = "df-analyze"
version = "0.1.0"
description = ""
authors = ["Derek M Berger <dmberger.dev@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.9,<=3.10"
coverage = "^7.3.2"
featuretools = "^1.28.0"
joblib = "^1.3.2"
matplotlib = "^3.8.1"
numpy = "^1.24.4"
optuna = "^3.4.0"
pandas = "^2.1.2"
pytest = "^7.4.3"
scikit-learn = "^1.3.2"
scipy = "^1.11.3"
tabulate = "^0.9.0"
typing-extensions = "^4.8.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
